# Site settings
title: Noom Design Resources
email: dux@noom.com
description: > # this means to ignore newlines until "baseurl:"
  All things Noom design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.noom.com/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
