# Site settings
title: Noom Design Resources
email: dux@noom.com
description: > # this means to ignore newlines until "baseurl:"
  All things Noom design.
baseurl: "/design" # the subpath of your site, e.g. /blog/
url: "http://noom.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
